### PR TITLE
chore: remove old content, leave redirects in place

### PR DESCRIPTION
**Pull request by varl**

### CODE REVIEW

**Comment by amcgee** [comment]
@varl seems like a good change!  How does this actually accomplish the redirect though?  I must me missing it but not sure how [this](https://github.com/dhis2/dhis2.github.io/pull/49/files#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883L36) gives a redirect destination?

**Comment by varl** [comment]
There used to be a hard coded link in various places around DHIS2 to the old docs hosted here: https://dhis2.github.io/dhis2-docs/master/en/user/html/dhis2_user_manual_en.html

When the docs then moved those hard links broke, so we had to set up a redirect here to the new docs at: https://docs.dhis2.org/

We did so using a module for Jekyll named `jekyll-redirect-from` which is a `meta`-tag based redirect that happens in the browser without configuring e.g. 301 redirects, which is tricky to set up using GitHub Pages.

The way it works is that we add a file with frontmatter in the `redirects` folder that states where the redirect should happen from and to, e.g.: https://raw.githubusercontent.com/dhis2/dhis2.github.io/master/redirects/dhis2_user_manual_en.md

This is already setup, so this PR just avoided removing those pieces.

After this PR the repo will look like this:

```
varl@veronika:~/dev/dhis2/docs/dhis2.github.io$ tree .
.
├── 404.html
├── _config.yml
├── Gemfile
├── Gemfile.lock
├── README.md
└── redirects
    └── dhis2_user_manual_en.md

1 directory, 6 files
```

**Comment by varl** [comment]
The way a redirect looks is like this:

```
curl https://dhis2.github.io/dhis2-docs/master/en/user/html/dhis2_user_manual_en.html
<!DOCTYPE html>
<html lang="en-US">
  <meta charset="utf-8">
  <title>Redirecting&hellip;</title>
  <link rel="canonical" href="/redirects/dhis2_user_manual_en/">
  <script>location="/redirects/dhis2_user_manual_en/"</script>
  <meta http-equiv="refresh" content="0; url=/redirects/dhis2_user_manual_en/">
  <meta name="robots" content="noindex">
  <h1>Redirecting&hellip;</h1>
  <a href="/redirects/dhis2_user_manual_en/">Click here if you are not redirected.</a>
</html>
```

For browsers that respect `meta`-tag redirects you don't see the HTML above, it just redirects. If the browser doesn't support `meta`-tag redirects, then the HTML is printed and waits for user action.

**Comment by amcgee** [comment]
Got it, thanks - I think I misunderstood this PR then, I thought this was supposed to ADD redirects from the old developer portal to the new one.  Keeping the existing docs redirect is a must of course.

That's something we might want to do... especially for links to i.e. the Cross-Site Cookies blogpost which gets thrown around a lot, we want to make sure that redirects to the proper post on developers.dhis2.org

Obviously since this is no longer CNAME'd from `developers.dhis2.org` it's minimally useful to implement the redirects here (`dhis2.github.io` only), but maybe we should use this content to generate the list of redirects in Docusaurus?

**Comment by deboragaleano** [comment]
@varl @amcgee  I apologize for my super late response on this! 

For redirecting from old-dev-portal to the new-dev-portal, maybe we could use the same Jekyll plugin `jekyll-redirect-from` to redirect blog posts and other documents individually (there are not that many). 

If we add `redirect_to` to every file (see [plugin](https://github.com/jekyll/jekyll-redirect-from#redirect-to) docs), this should redirect to the correct URL: 

```
---
title: SameSite Cookie Policies and DHIS2 Applications
redirect_to: https://developers.dhis2.org/blog/cross-origin-cookies/
```
So it would look like this: 

redirect

I don't mind doing this for the rest of the files if you think that this is an option? Maybe in a separate PR?

**Comment by varl** [comment]
@deboragaleano hehe -- sorry about the late response on this, too !

That's a very good idea !

**Comment by deboragaleano** [comment]
@varl I created this [PR](https://github.com/dhis2/dhis2.github.io/pull/51) for each post/doc redirects. I'm not sure which PR should be merged first though 🤔

**Comment by varl** [comment]
@deboragaleano I created a third branch that I merged this #49 and #51 into, and we can merge #52 to `master`.

**Pull request closed without merging**
