### PR TITLE
docs: add ui-core v4 release notes

### PR DESCRIPTION
**Pull request by ismay**
Closes https://jira.dhis2.org/browse/TECH-273

Post to announce the release of ui-core v4, give some background info and note the most important changes to look out for when upgrading.

### CODE REVIEW

**Comment by cooper-joe** [comment]
Here is some text that explains why the input fields were changed. I'm not sure where it should live in the document. What do you think @ismay?

```
###Why have the input fields changed?

There are three main reasons for the breaking change in input fields:

1. the previous inputs were not recognizable enough as inputs for all users
2. there were no good reasons to maintain multiple input styles
3. the filled and outlined inputs sometimes interchanged the use of labels and/or placeholder text. This needed to be simplified to define clearly the roles of the label and placeholder.

The previous filled and outlined inputs were inherited from our use of Material UI. When building our own UI library we have been able to create an input component that is right for DHIS2 applications. The new input component is:

- recognizable: it looks and behaves like input fields most users are familiar with
- understandable: there are no animations or moving parts to distract from its core use
- using obvious label and placeholder texts: a label is always above, a placeholder text is always within. Using one does not affect the other.
```

**Comment by ismay** [comment]
@cooper-joe Thanks for the text, I've added it to the post. Let me know what you think!

**Comment by cooper-joe** [comment]
Looks good @ismay. A nice overview of the changes. I think one thing that could be useful is explaining what will happen to any old inputs that are still used. Will all `<Input filled>` inputs now default to the new style, or is this something that needs to be done manually? Perhaps this is self-explanatory to any dev using a library, but I'm personally unsure.

**Comment by ismay** [comment]
> Looks good @ismay. A nice overview of the changes. I think one thing that could be useful is explaining what will happen to any old inputs that are still used. Will all `<Input filled>` inputs now default to the new style, or is this something that needs to be done manually? Perhaps this is self-explanatory to any dev using a library, but I'm personally unsure.

Ah yeah, yeah we can add that. Since the filled prop has been completely removed from Input, Input will just ignore it (I assume the same has been done for other components that build on it). Probably still good to remind devs to remove the filled prop, even though everything looks all right from a UI perspective.

**Comment by ismay** [comment]
Nice, thanks for the feedback! I've added your suggestions.

**Comment by varl** [comment]
Looks good! Thanks for drafting this.

**Pull request merged**
